src/Entity/Basket.php
<?php

namespace App\Entity;

use App\Repository\BasketRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BasketRepository::class)]
class Basket
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Product::class, inversedBy: 'baskets')]
    private $Product;

    #[ORM\ManyToOne(targetEntity: User::class, inversedBy: 'Basket')]
    private $User;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduct(): ?Product
    {
        return $this->Product;
    }

    public function setProduct(?Product $Product): self
    {
        $this->Product = $Product;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Accueil{% endblock %}</title>
        <link rel="icon" href="/../img/logo.png">
        <link rel="stylesheet" href="/style.css">
        <html lang="fr" xml:lang="fr" xmlns="http://www.w3.org/1999/xhtml">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        <nav class="container desktop">
            <div class="row align-items-start">
                <div class="col tleft">
                    <img class="logo" src="/../img/logo.png" alt="image du logo">
                    <div class="column lcolumn">
                        <a class="navlink" href="{{path('home')}}">Nozama</a>
                        <a class="navlink" href="{{path('about')}}">A propos</a>
                    </div>
                </div>
                <div class="col tright">
                <div class="column">
                    {% if app.user %}
                    <a class="navlink" href="{{path('basket')}}">Mon panier</a>
                    <a class="navlink" href="{{path('app_logout')}}">Deconnection</a>
                    {% endif %}
                    {% if not app.user %}
                    <a class="navlink" href="{{path('app_login')}}">Se connecter</a>
                    <a class="navlink" href="{{path('app_register')}}">S'enregistrer</a>
                    {% endif %}
                </div>
                </div>
            </div>
        </nav>

        <div class="middle">
        {% block body %}{% endblock %}
        </div>
    </body>
</html>